@startuml instructionsActivity

start
repeat
  :put X;
  :put O;
repeat while (areThere two X on board)
:put X;
if (isTicTacToe?) then (yes)
else (no)
  :put O;
  while (!isTicTacToe) is (yes)
    :put X;
    if (!isTicTacToe) then (yes)
    else (no)
    :put O;
    endif
  endwhile (no)
endif

stop

@enduml